Loading tfidf pipes
Traceback (most recent call last):
  File "/scratchB/oqcardoso/gvc-testfinal/unsummarized/p-script.py", line 436, in <module>
    both_csv = deepSetPredictions(both_loader, model_state_path ,input_size, max_len_brief, "both")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratchB/oqcardoso/gvc-testfinal/unsummarized/p-script.py", line 120, in deepSetPredictions
    model.load_state_dict(torch.load(model_state_path))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratchB/oqcardoso/.pyenv/versions/3.11.4/lib/python3.11/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratchB/oqcardoso/.pyenv/versions/3.11.4/lib/python3.11/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratchB/oqcardoso/.pyenv/versions/3.11.4/lib/python3.11/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'models/DeepSets_both_tfidf.pth'
